import type { CardProps } from "@/types/types";

export const mockCards: CardProps[] = [
  {
    id: "1",
    title: "샘플 카드 1",
    status: "todo",
    priority: "low",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    description: "설명 1",
    tags: ["sample", "test"],
    assignee: "홍길동",
  },
  {
    id: "2",
    title: "샘플 카드 2",
    status: "in-progress",
    priority: "medium",
    createdAt: "2024-01-02",
    updatedAt: "2024-01-02",
    description: "설명 2",
    tags: ["sample"],
    assignee: "김철수",
  },
  {
    id: "3",
    title: "샘플 카드 3",
    status: "done",
    priority: "high",
    createdAt: "2024-01-03",
    updatedAt: "2024-01-03",
    description: "설명 3",
    tags: ["test"],
    assignee: "이영희",
  },
  {
    id: "4",
    title: "샘플 카드 4",
    status: "todo",
    priority: "low",
    createdAt: "2024-01-04",
    updatedAt: "2024-01-04",
    description: "설명 4",
    tags: [],
    assignee: "홍길동",
  },
  {
    id: "5",
    title: "샘플 카드 5",
    status: "in-progress",
    priority: "medium",
    createdAt: "2024-01-05",
    updatedAt: "2024-01-05",
    description: "설명 5",
    tags: ["sample"],
    assignee: "김철수",
  },
  {
    id: "6",
    title: "샘플 카드 6",
    status: "done",
    priority: "high",
    createdAt: "2024-01-06",
    updatedAt: "2024-01-06",
    description: "설명 6",
    tags: ["test"],
    assignee: "이영희",
  },
  {
    id: "7",
    title: "샘플 카드 7",
    status: "todo",
    priority: "low",
    createdAt: "2024-01-07",
    updatedAt: "2024-01-07",
    description: "설명 7",
    tags: [],
    assignee: "홍길동",
  },
  {
    id: "8",
    title: "샘플 카드 8",
    status: "in-progress",
    priority: "medium",
    createdAt: "2024-01-08",
    updatedAt: "2024-01-08",
    description: "설명 8",
    tags: ["sample"],
    assignee: "김철수",
  },
  {
    id: "9",
    title: "샘플 카드 9",
    status: "done",
    priority: "high",
    createdAt: "2024-01-09",
    updatedAt: "2024-01-09",
    description: "설명 9",
    tags: ["test"],
    assignee: "이영희",
  },
  {
    id: "10",
    title: "샘플 카드 10",
    status: "todo",
    priority: "low",
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10",
    description: "설명 10",
    tags: [],
    assignee: "홍길동",
  },
];

export const mockColumns = [
  {
    id: "1",
    title: "To Do",
    cards: mockCards.filter((card) => card.status === "todo"),
  },
  {
    id: "2",
    title: "In Progress",
    cards: mockCards.filter((card) => card.status === "in-progress"),
  },
  {
    id: "3",
    title: "Done",
    cards: mockCards.filter((card) => card.status === "done"),
  },
];
